---
# Source: wordpress/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.4.3
    helm.sh/chart: wordpress-19.4.3
type: Opaque
data:
  wordpress-password: "MTIzNDU2YUBB"
